version: '3'

services:
  
  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:11'
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  # #  启动 MongoDB，并确保数据存储到挂载卷
  # mongodb:
  #   image: 'mongo:latest'
  #   ports:
  #     - "27017:27017"
  #   restart: always
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root123
  #   volumes:
  #     - ./db-data/mongodb/:/data/db

  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data

  # #  start mailhog
  # mailhog:
  #   image: 'mailhog/mailhog:latest'
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   restart: always